download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/infra-quay_configuration-2.5.0.tar.gz
format_version: 1.0.0
name: quay_configuration
namespace: infra
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.5.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/infra/quay_configuration/versions/2.5.0/
